version: '3.9'

volumes:
  mongodb_data: { }

networks:
  internal:
    external: false

services:
  go-api:
    container_name: go-app
    build:
      context: .
      dockerfile: ./compose/go/Dockerfile
    ports:
      - "${GO_API_PORT}:8080"
    env_file:
      - ./.env
    networks:
      - internal
    depends_on:
      - go-mongodb
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: always

  go-mongodb:
    container_name: mongodb
    image: mongo
    env_file:
      - ./.env
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "${MONGODB_EXPRESS_PORT}:8081"
    env_file:
      - ./.env
    networks:
      - internal